# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/kuttans.ui'
#
# Created: Sat Feb 14 00:01:16 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Kuttans(object):
    def setupUi(self, Kuttans):
        Kuttans.setObjectName("Kuttans")
        Kuttans.resize(631, 390)
        self.centralwidget = QtGui.QWidget(Kuttans)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        Kuttans.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Kuttans)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Convert = QtGui.QMenu(self.menubar)
        self.menu_Convert.setObjectName("menu_Convert")
        self.menu_Unicode_To_ASCII = QtGui.QMenu(self.menu_Convert)
        self.menu_Unicode_To_ASCII.setObjectName("menu_Unicode_To_ASCII")
        self.menu_ASCII_To_Unicode = QtGui.QMenu(self.menu_Convert)
        self.menu_ASCII_To_Unicode.setObjectName("menu_ASCII_To_Unicode")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        Kuttans.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Kuttans)
        self.statusbar.setObjectName("statusbar")
        Kuttans.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Kuttans)
        self.toolBar.setObjectName("toolBar")
        Kuttans.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.editToolBar = QtGui.QToolBar(Kuttans)
        self.editToolBar.setObjectName("editToolBar")
        Kuttans.addToolBar(QtCore.Qt.TopToolBarArea, self.editToolBar)
        self.actionOpen = QtGui.QAction(Kuttans)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Kuttans/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtGui.QAction(Kuttans)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Kuttans/window-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtGui.QAction(Kuttans)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Kuttans/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(Kuttans)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Kuttans/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon3)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionKuttansHelp = QtGui.QAction(Kuttans)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Kuttans/system-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKuttansHelp.setIcon(icon4)
        self.actionKuttansHelp.setObjectName("actionKuttansHelp")
        self.actionPayyansHelp = QtGui.QAction(Kuttans)
        self.actionPayyansHelp.setIcon(icon4)
        self.actionPayyansHelp.setObjectName("actionPayyansHelp")
        self.actionAbout = QtGui.QAction(Kuttans)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Kuttans/face-confused.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.actionASCIIToUnicode = QtGui.QAction(Kuttans)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Kuttans/preferences-desktop-font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionASCIIToUnicode.setIcon(icon6)
        self.actionASCIIToUnicode.setObjectName("actionASCIIToUnicode")
        self.actionCopy = QtGui.QAction(Kuttans)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Kuttans/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon7)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtGui.QAction(Kuttans)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Kuttans/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon8)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(Kuttans)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Kuttans/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon9)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo = QtGui.QAction(Kuttans)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Kuttans/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon10)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(Kuttans)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Kuttans/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon11)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSelectAll = QtGui.QAction(Kuttans)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Kuttans/edit-select-all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectAll.setIcon(icon12)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionSelectFontMap_u2a = QtGui.QAction(Kuttans)
        self.actionSelectFontMap_u2a.setIcon(icon6)
        self.actionSelectFontMap_u2a.setObjectName("actionSelectFontMap_u2a")
        self.actionSelectFontMap_a2u = QtGui.QAction(Kuttans)
        self.actionSelectFontMap_a2u.setIcon(icon6)
        self.actionSelectFontMap_a2u.setObjectName("actionSelectFontMap_a2u")
        self.actionRevathi_u2a = QtGui.QAction(Kuttans)
        self.actionRevathi_u2a.setIcon(icon6)
        self.actionRevathi_u2a.setObjectName("actionRevathi_u2a")
        self.actionIndulekha_u2a = QtGui.QAction(Kuttans)
        self.actionIndulekha_u2a.setIcon(icon6)
        self.actionIndulekha_u2a.setObjectName("actionIndulekha_u2a")
        self.actionKarthika_u2a = QtGui.QAction(Kuttans)
        self.actionKarthika_u2a.setIcon(icon6)
        self.actionKarthika_u2a.setObjectName("actionKarthika_u2a")
        self.actionRevathi_a2u = QtGui.QAction(Kuttans)
        self.actionRevathi_a2u.setIcon(icon6)
        self.actionRevathi_a2u.setObjectName("actionRevathi_a2u")
        self.actionIndulekha_a2u = QtGui.QAction(Kuttans)
        self.actionIndulekha_a2u.setIcon(icon6)
        self.actionIndulekha_a2u.setObjectName("actionIndulekha_a2u")
        self.actionKarthika_a2u = QtGui.QAction(Kuttans)
        self.actionKarthika_a2u.setIcon(icon6)
        self.actionKarthika_a2u.setObjectName("actionKarthika_a2u")
        self.actionPrint = QtGui.QAction(Kuttans)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Kuttans/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon13)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExportPDF = QtGui.QAction(Kuttans)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Kuttans/application-illustrator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportPDF.setIcon(icon14)
        self.actionExportPDF.setObjectName("actionExportPDF")
        self.actionPrintPreview = QtGui.QAction(Kuttans)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Kuttans/document-print-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrintPreview.setIcon(icon15)
        self.actionPrintPreview.setObjectName("actionPrintPreview")
        self.actionDelete = QtGui.QAction(Kuttans)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Kuttans/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon16)
        self.actionDelete.setObjectName("actionDelete")
        self.actionNew = QtGui.QAction(Kuttans)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Kuttans/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon17)
        self.actionNew.setObjectName("actionNew")
        self.actionASCIIToUnicodePDF = QtGui.QAction(Kuttans)
        self.actionASCIIToUnicodePDF.setIcon(icon14)
        self.actionASCIIToUnicodePDF.setObjectName("actionASCIIToUnicodePDF")
        self.actionUnicodeToASCIIPDF = QtGui.QAction(Kuttans)
        self.actionUnicodeToASCIIPDF.setIcon(icon14)
        self.actionUnicodeToASCIIPDF.setObjectName("actionUnicodeToASCIIPDF")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportPDF)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrintPreview)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menu_Unicode_To_ASCII.addAction(self.actionRevathi_u2a)
        self.menu_Unicode_To_ASCII.addAction(self.actionIndulekha_u2a)
        self.menu_Unicode_To_ASCII.addAction(self.actionKarthika_u2a)
        self.menu_Unicode_To_ASCII.addAction(self.actionSelectFontMap_u2a)
        self.menu_ASCII_To_Unicode.addAction(self.actionRevathi_a2u)
        self.menu_ASCII_To_Unicode.addAction(self.actionIndulekha_a2u)
        self.menu_ASCII_To_Unicode.addAction(self.actionKarthika_a2u)
        self.menu_ASCII_To_Unicode.addAction(self.actionSelectFontMap_a2u)
        self.menu_Convert.addAction(self.menu_ASCII_To_Unicode.menuAction())
        self.menu_Convert.addAction(self.menu_Unicode_To_ASCII.menuAction())
        self.menu_Convert.addSeparator()
        self.menu_Convert.addAction(self.actionASCIIToUnicodePDF)
        self.menu_Convert.addAction(self.actionUnicodeToASCIIPDF)
        self.menu_Help.addAction(self.actionKuttansHelp)
        self.menu_Help.addAction(self.actionPayyansHelp)
        self.menu_Help.addAction(self.actionAbout)
        self.menu_Edit.addAction(self.actionCopy)
        self.menu_Edit.addAction(self.actionCut)
        self.menu_Edit.addAction(self.actionPaste)
        self.menu_Edit.addAction(self.actionDelete)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionUndo)
        self.menu_Edit.addAction(self.actionRedo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionSelectAll)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Convert.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionExportPDF)
        self.toolBar.addAction(self.actionPrint)
        self.editToolBar.addAction(self.actionCopy)
        self.editToolBar.addAction(self.actionCut)
        self.editToolBar.addAction(self.actionPaste)
        self.editToolBar.addAction(self.actionUndo)
        self.editToolBar.addAction(self.actionRedo)

        self.retranslateUi(Kuttans)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated(int)"), Kuttans.close)
        QtCore.QObject.connect(self.actionCopy, QtCore.SIGNAL("activated(int)"), self.textEdit.copy)
        QtCore.QObject.connect(self.actionCut, QtCore.SIGNAL("activated(int)"), self.textEdit.cut)
        QtCore.QObject.connect(self.actionPaste, QtCore.SIGNAL("activated(int)"), self.textEdit.paste)
        QtCore.QObject.connect(self.actionUndo, QtCore.SIGNAL("activated(int)"), self.textEdit.undo)
        QtCore.QObject.connect(self.actionRedo, QtCore.SIGNAL("activated(int)"), self.textEdit.redo)
        QtCore.QObject.connect(self.actionSelectAll, QtCore.SIGNAL("activated(int)"), self.textEdit.selectAll)
        QtCore.QMetaObject.connectSlotsByName(Kuttans)

    def retranslateUi(self, Kuttans):
        Kuttans.setWindowTitle(QtGui.QApplication.translate("Kuttans", "Kuttans", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Kuttans", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Convert.setTitle(QtGui.QApplication.translate("Kuttans", "&Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Unicode_To_ASCII.setTitle(QtGui.QApplication.translate("Kuttans", "&Unicode To ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_ASCII_To_Unicode.setTitle(QtGui.QApplication.translate("Kuttans", "&ASCII to Unicode", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("Kuttans", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("Kuttans", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Kuttans", "Main Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.editToolBar.setWindowTitle(QtGui.QApplication.translate("Kuttans", "Edit Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("Kuttans", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("Kuttans", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Kuttans", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("Kuttans", "Save &As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKuttansHelp.setText(QtGui.QApplication.translate("Kuttans", "&Kuttans Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPayyansHelp.setText(QtGui.QApplication.translate("Kuttans", "&Payyans Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("Kuttans", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASCIIToUnicode.setText(QtGui.QApplication.translate("Kuttans", "&ASCII To Unicode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("Kuttans", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("Kuttans", "C&ut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("Kuttans", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("Kuttans", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("Kuttans", "&Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setText(QtGui.QApplication.translate("Kuttans", "&Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectFontMap_u2a.setText(QtGui.QApplication.translate("Kuttans", "&Custom Font map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectFontMap_a2u.setText(QtGui.QApplication.translate("Kuttans", "&Custom Font map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRevathi_u2a.setText(QtGui.QApplication.translate("Kuttans", "&Revathi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIndulekha_u2a.setText(QtGui.QApplication.translate("Kuttans", "&Indulekha", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKarthika_u2a.setText(QtGui.QApplication.translate("Kuttans", "&Karthika", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRevathi_a2u.setText(QtGui.QApplication.translate("Kuttans", "&Revathi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIndulekha_a2u.setText(QtGui.QApplication.translate("Kuttans", "&Indulekha", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKarthika_a2u.setText(QtGui.QApplication.translate("Kuttans", "&Karthika", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("Kuttans", "&Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setText(QtGui.QApplication.translate("Kuttans", "&Export As PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPreview.setText(QtGui.QApplication.translate("Kuttans", "P&rint Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("Kuttans", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("Kuttans", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASCIIToUnicodePDF.setText(QtGui.QApplication.translate("Kuttans", "ASCII &PDF to Unicode PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnicodeToASCIIPDF.setText(QtGui.QApplication.translate("Kuttans", "Unicode P&DF to ASCII PDF", None, QtGui.QApplication.UnicodeUTF8))

import kuttans_rc
