#!/bin/sh
# vim:set noet ts=4:
#
# ibus-tmpl - The Input Bus template project
#
# Copyright (c) 2007-2008 Huang Peng <shawn.p.huang@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
prefix=/usr
exec_prefix=${prefix}
libexecdir=${exec_prefix}/libexec
pyexecdir=${exec_prefix}/lib/python2.5/site-packages
export PYTHONPATH=${exec_prefix}/lib/python2.5/site-packages:$PYTHONPATH
export IBUS_SULEKHA_LOCATION=/usr/share/ibus-sulekha
export LIBEXECDIR=$libexecdir
exec python /usr/share/ibus-sulekha/engine/main.py $@

