/*Copyright (c) 2008, Rajeesh K Nambiar							*
 *											*
 * Chathans is a free software; you can redistribute it and/or modify it under the terms*
 * of GNU General Public License as published by the Free Software Foundation, either	*
 * version 3 of the License, or (at your option) any later version.			*
 *											*
 * Chathans is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;*
 * without even implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.*
 * See the GNU General Public License for more details.					*
 */

/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
