/*Copyright (c) 2008, Rajeesh K Nambiar							*
 *											*
 * Chathans is a free software; you can redistribute it and/or modify it under the terms*
 * of GNU General Public License as published by the Free Software Foundation, either	*
 * version 3 of the License, or (at your option) any later version.			*
 *											*
 * Chathans is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;*
 * without even implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.*
 * See the GNU General Public License for more details.					*
 */

/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"

int
main (int argc, char *argv[])
{
  GtkWidget *MainWindow;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  MainWindow = create_MainWindow ();
  gtk_widget_show (MainWindow);

  initialize_widgets(MainWindow);

  gtk_main ();
  return 0;
}

